# Generated by Django 4.1.6 on 2023-02-11 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('machine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.FloatField()),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
